channels:
  - pyviz
  - conda-forge
dependencies:
  - scipy == 1.5.2
  - scikit-learn == 0.23.2
  - param == 1.10.1
  - panel == 0.9.5
  - pandas == 1.1.3
  - numpy == 1.19.1
  - bokeh == 2.0.0
  - matplotlib == 3.3.4
  - emagpy 1.1.0
  
packages:
- jupyter-panel-proxy
